config/routes.rb
Rails.application.routes.draw do
  root to: 'static_page#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'static_page/home', to: 'static_page#home'
  resources :users
  get 'private', to: 'static_page#private'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #User.find_by(id: session[:user_id])
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'La combinaison email/mot de passe est invalide'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def private
    if logged_in?
    else
      flash[:danger] = "Le contenu n'est accessible qu'aux personnes connectées"
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def show
    if logged_in? && @current_user.id == @user.id
    elsif logged_in?
      redirect_to root_path
      flash[:danger] = "Tu ne peux pas accéder à ces informations."
    else
      redirect_to login_path
      flash[:danger] = "Tu dois être connecté pour accéder à ces informations."
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash.now[:success] = "Connexion réussie"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    if logged_in? && @current_user.id == @user.id
    elsif logged_in?
      redirect_to root_path
      flash[:danger] = "Tu ne peux pas accéder à ces informations."
    else
      redirect_to login_path
      flash[:danger] = "Tu dois être connecté(e) pour accéder à ces informations."
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav">
          <li class="nav-item active"><%= link_to "Accueil", root_path, class:'nav-link' %></li>
          <% if logged_in? %>
            <li class="nav-item"><%= link_to "Club", '#', class:'nav-link' %></li>
            <li class="nav-item"><%= link_to "Connecté en tant que #{@current_user.first_name}", user_path(@current_user), class:'nav-link' %></li>
            <li class="nav-item"><%= link_to "Se déconnecter", logout_path, method: :delete, class:'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Se connecter", login_path, class:'nav-link' %></li>
            <li class="nav-item"><%= link_to "Créer un compte", new_user_path, class:'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |type, msg| %>
    <%= content_tag(:div,msg,class:"alert alert-#{type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le formulaire contient <%= pluralize(@user.errors.count, "erreur") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/home.html.erb
<div class="container">
  <% if logged_in? %>
    <h1 class="text-center">Bienvenue <%= @current_user.first_name %> !</h1>
    <p class="text-center"><%= link_to "Le club", private_path%>.</p>
  <% else %>
    <h1 class="text-center">Bienvenue!</h1>
    <p class="text-center"> <%=link_to "Connexion", login_path%> ou <%=link_to "Créer un compte", new_user_path%>.</p>
  <% end %>
</div>

app/views/static_page/private.html.erb
<h1 class="text-center">Tous les membres</h1><br/>
  <div class="container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Adresse email</th>
          </tr>
        </thead>
        <tbody>
      <% User.all.each do |user| %>
        <tr>
          <th scope="row"><%= user.last_name %></th>
          <th scope="row"><%= user.first_name %></th>
          <th scope="row"><%= user.email %></th>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

app/views/users/edit.html.erb
<h1 class="text-center">Modifie ton profil</h1>
<div class="container">
<%= form_for @user do |f| %>

<%= f.label :first_name, "Prénom"%><br/>
<%= f.text_field :first_name, class:"form-control"%><br/>

<%= f.label :last_name, "Nom"%><br/>
<%= f.text_field :last_name, class:"form-control" %><br/>

<%= f.label :email, "Adresse email"%><br/>
<%= f.email_field :email, class:"form-control" %><br/>

<p class="text-center"><%= f.submit "Editer mon profil", class:"btn btn-outline-primary" %>

<%= link_to 'Supprimer mon profil', @user, method: :delete, class:"btn btn-outline-danger" %></p><br/>

<% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Création d'un compte</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name, 'Prénom' %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name, 'Nom' %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, 'Mot de passe' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, 'Confirmation du mot de passe' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br/>

      <%= f.submit "Log in", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p class="text-center">Comment ça va <%= @user.first_name %> ? </p> <br/>

<p class="text-center"> <strong> Informations:</strong></p> <br />

<div class="text-center">
  <table class="table table-borderless">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">Prénom</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.last_name %></td>
        <td><%= @user.first_name %></td>
        <td><%= @user.email %></td>
    </tbody>
  </table>
</div>

<p class="text-center"><%= link_to "Editer mon profil", edit_user_path, class: "btn btn-outline-primary" %> </p>

<p class="text-center"><%= link_to "Retour à l'accueil", root_path, class: "btn btn-outline-primary" %> </p>